version: '2'

services:
  postgres:
    restart: always
    image: kiasaki/alpine-postgres:9.5
    environment:
      - POSTGRES_USER:'user'
      - POSTGRES_PASSWORD:'password'
      - POSTGRES_DB:'postgres'
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: